#!/bin/bash


#The most basic script
#Really just here to test out scripting
#wal -qt -i '~/wallpapers'

usage() { printf "%s" "\
Usage: randesktop
Example: randesktop

Flags:
  -d                      dududududu
  -a                      dududududu
  -r                      dududududu
  -ud                     dududududu
  -e                      trololol

"
}

memes() { printf "%s" "\
trololol"
}

otherWallpapers() 
{ 

wal -qt -i '/home/domar/.gWallpapers'

}

get_args() {
    while getopts ":a:chi:o:qrt" opt; do
        case "$opt" in
            "a") alpha="$OPTARG" ;;
            "c") rm -rf "${cache_dir}/schemes"; exit ;;
            "h") usage; exit 1 ;;

            "i")
                [[ -f "${PWD}/${OPTARG/*\/}" ]] && wal="${PWD}/${OPTARG/*\/}"
                [[ -z "$wal" ]] && wal="$(get_full_path "$OPTARG")"
            ;;

            "o") external_script=("$OPTARG") ;;
            "q") quiet="on" ;;
            "r") otherWallpapers; exit 1 ;;
            "t") memes ;;

            "?")
                printf "%s\n" "Invalid option: -$OPTARG" >&2
                exit 1
            ;;

            ":")
                printf "%s\n" "Option -$OPTARG requires an argument." >&2
                exit 1
            ;;
        esac
    done
}

main () {

	get_args "$@"

    wal -qt -i '/home/domar/wallpapers'

    #echo "Wallpaper changed!"
}

main "$@"